### ISSUE TITLE
Dask 2024.5.1 removed `.attrs`

### ISSUE THREAD

**Issue by LucaMarconato** [dask/dask#11146]
The latest release removed `.attrs`. This breaks backward compatibility and also Pandas still uses it, so I kindly ask if it can be reinstated.

To reproduce, the last assert should pass.
```python
import dask.dataframe as dd
df = dd.from_pandas(pd.DataFrame())
assert hasattr(df.compute(), 'attrs') == True
assert hasattr(df, 'attrs') == True
```

**Environment**:

- Dask version: 2024.5.1
- Python version: 3.12.2
- Operating System: macOS Sonoma 14.5
- Install method (conda, pip, source): conda

**Comment by phofl** [comment]
Thanks for the report.

Could you add a bit more context about what you are trying to achieve with attr? attr doesn't really work in pandas either and support is spotty at most.

**Comment by LucaMarconato** [comment]
I also experienced a problem with `pandas` and `.attrs`: copied `DataFrame` objects where not containing a copy of `.attrs`. (I initially thought it was a `geopandas` problem https://github.com/geopandas/geopandas/issues/2920), but then it turned out to be from `pandas` https://github.com/pandas-dev/pandas/issues/54134. Fortunately the bug above is now fixed. Which other problems did you find?

The use case for `.attrs` we have in the library we developed https://github.com/scverse/spatialdata/, is to store metadata associated to `GeoDataFrame` and `DataFrame` objects (both lazy and non-lazy). The metadata mostly contain json-like information that describes how various spatial objects are aligned together.

**Comment by LucaMarconato** [comment]
Do you have any update on this? 😊 Some users reported problems with installation due to having pinned an older version of Dask in our config so it's an important issue for us. Thank you for your time.

**Comment by phofl** [comment]
This is non-trivial to add and the semantics aren't completely clear either. This can't live on the collection level, it has to be on the expression level since we are constantly recreating the underlying expression, which makes it non-trivial. That said, the following is unclear to me:

```
df = dd.from_pandas(...)
df.attrs = "foo"
df = df.fillna(100)
df = df["a"]
df.attrs = "bar"
```

dask-expr will reorder the query and push the projection in front of the fillna. So what attr should take precedence here?

Contributions are very welcome. I won't have much time to think about this though

**Comment by LucaMarconato** [comment]
Thanks for the answer. From my understanding (and for the purpose of our use case) the `df.attrs` slot should not be treated as lazy but always be executed immediately. This was the behavior implemented before Dask 2024.5.1. In particular in your example the computational graph would never contain nodes related to modifying `.atttrs`.

I think making a PR for this should be quick, if you agree with this semantic I could give it a try.

**Comment by phofl** [comment]
That would be fine but this still doesn't cover what should happen after df.optimize() is called, which is the tricky part here

**Comment by LucaMarconato** [comment]
I will try making some experiments and get back to you.

**Comment by fjetter** [comment]
> This can't live on the collection level, it has to be on the expression level

can you elaborate? My initial gut reaction is that this should only live on the collection level and not on expr. 

--

https://github.com/pandas-dev/pandas/issues/52166 reads like there are a lot of questions around this feature and I wouldn't be surprised if some of this is subject to change.

**Comment by phofl** [comment]
> can you elaborate? My initial gut reaction is that this should only live on the collection level and not on expr.

We constantly re-create the expressions underneath the collection, creating completely new collections in the optimiser. Ensuring that this propagates seems non-trivial if the information is only available on the collection.

**Comment by hendrikmakait** [comment]
> We constantly re-create the expressions underneath the collection, creating completely new collections in the optimiser. Ensuring that this propagates seems non-trivial if the information is only available on the collection.

Are we ever interested in maintaining the correct value of `.attrs` for any intermediate expression or only in its value on the root collection? In the latter case, attaching it to the collection and fixing it during the optimization step feels manageable.

**Comment by LucaMarconato** [comment]
> I will try making some experiments and get back to you.

I made some experiments but never reported here.

> Are we ever interested in maintaining the correct value of .attrs for any intermediate expression or only in its value on the root collection? In the latter case, attaching it to the collection and fixing it during the optimization step feels manageable.

I tried this but, TLDR, I didn't manage to make it work and ended up temporarily disabling the new backend (here is a more elaborate comment of what I tried: https://github.com/scverse/spatialdata/pull/570#issuecomment-2187577322). 

Now with the latest release 2024.11.01, the old backend is disabled and and we would lose access to `.attrs`, which plays a key role in the `spatialdata` library. 

Do you have any update on this? Could you please try a fix? Please notice that as shown in the discussion here https://github.com/pandas-dev/pandas/issues/52166, there are many developers that are relying on `.attrs` in `pandas`, and therefore not having this available in `dask.dataframes` may prevent its use for them as well.
