### ISSUE TITLE
Memory issue after dask.persist()

### ISSUE THREAD

**Issue by jierice** [dask/dask#2625]
Hi,

I have a script using `dask`. When I run the script, I found the memory will blow up over time. So I do some experiments. I find I couldn't release the memory after `persist`. Below is my minimal working example.
 
```
In [1]: import numpy as np
In [2]: import dask.array as da
In [3]: import dask
In [4]: import psutil

In [5]: psutil.virtual_memory()
Out[5]: svmem(total=135289647104, available=67503648768, percent=50.1, used=67343593472, free=62600888320, active=63765585920, inactive=7044632576, buffers=58826752, cached=5286338560, shared=96567296)

In [6]: data = np.random.rand(1000,1000,1000)

In [7]: psutil.virtual_memory()
Out[7]: svmem(total=135289647104, available=59508670464, percent=56.0, used=75338403840, free=54605930496, active=71748612096, inactive=7044825088, buffers=58871808, cached=5286440960, shared=96567296)

In [8]: del(data)

In [9]: psutil.virtual_memory()
Out[9]: svmem(total=135289647104, available=67523821568, percent=50.1, used=67323244544, free=62621016064, active=63749652480, inactive=7044861952, buffers=58888192, cached=5286498304, shared=96567296)
```
Now it's working properly. When I delete the data, the memory will be released. However, if I do sth like below.
```
In [10]: data = np.random.rand(1000,1000,1000)

In [11]: psutil.virtual_memory()
Out[11]: svmem(total=135289647104, available=59507421184, percent=56.0, used=75339649024, free=54604402688, active=71752163328, inactive=7045079040, buffers=58945536, cached=5286649856, shared=96571392)

In [12]: chunkdata = da.from_array(data,chunks=(200,200,950)).persist(get=dask.threaded.get)

In [13]: psutil.virtual_memory()
Out[13]: svmem(total=135289647104, available=59479982080, percent=56.0, used=75367088128, free=54576783360, active=71779045376, inactive=7045165056, buffers=58986496, cached=5286789120, shared=96571392)

In [14]: del(data)

In [15]: psutil.virtual_memory()
Out[15]: svmem(total=135289647104, available=59491192832, percent=56.0, used=75355877376, free=54587940864, active=71767511040, inactive=7045185536, buffers=59002880, cached=5286825984, shared=96571392)

In [16]: del(chunkdata)

In [17]: psutil.virtual_memory()
Out[17]: svmem(total=135289647104, available=59491373056, percent=56.0, used=75355697152, free=54588071936, active=71768121344, inactive=7045271552, buffers=59019264, cached=5286858752, shared=96571392)
```

The memory will never be released. And if I do this in a loop, it will blow up the memory.

**Comment by mrocklin** [comment]
Can I ask you to try this with plain `python` rather than with `ipython`?  IPython sometimes holds onto intermediate values in confusing ways.

**Comment by mrocklin** [comment]
It looks like a few of the tasks get stuck in memory, I suspect somewhere in the `ThreadPool`.  Flushing a few more tasks through the scheduler seems to clean them up.

```python
In [1]: import numpy as np
   ...: import dask
   ...: import dask.array as da
   ...: import psutil
   ...: import weakref
   ...: import sys
   ...: from toolz import frequencies
   ...: 

In [2]: x = np.random.random((1000, 1000))
In [3]: d = da.from_array(x, chunks=(100, 100))
In [4]: xr = weakref.ref(x)
In [5]: sys.getrefcount(xr())  # one for x, one for d, one for python
Out[5]: 3

In [6]: d = d.persist(get=dask.get)
In [7]: sys.getrefcount(xr())  # 100 new slices point back to x
Out[7]: 102

In [8]: wvd = weakref.WeakValueDictionary(d.dask)
In [9]: frequencies(map(sys.getrefcount, wvd.values()))
Out[9]: {3: 100}

In [10]: del d
In [11]: frequencies(map(sys.getrefcount, wvd.values()))   # this is what we expect
Out[11]: {}
In [12]: sys.getrefcount(xr())
Out[12]: 2

In [13]: d = da.from_array(x, chunks=(100, 100))  # lets do the same thing with a ThreadPool
In [14]: d = d.persist(get=dask.threaded.get)
In [15]: wvd = weakref.WeakValueDictionary(d.dask)
In [16]: frequencies(map(sys.getrefcount, wvd.values()))
Out[16]: {3: 97, 4: 3}

In [17]: del d
In [18]: frequencies(map(sys.getrefcount, wvd.values()))
Out[18]: {3: 3}

In [19]: sys.getrefcount(xr())
Out[19]: 8

In [20]: da.arange(10, chunks=(1,)).sum().compute()  # lets flush a few more tasks through
Out[20]: 45
In [21]: frequencies(map(sys.getrefcount, wvd.values()))
Out[21]: {}
```

cc @jcrist

**Comment by mrocklin** [comment]
Yeah, this is an issue in Python's `ThreadPool` implementation:

```python
In [1]: import numpy as np
   ...: import sys
   ...: import weakref
   ...: from multiprocessing.pool import ThreadPool
   ...: 

In [2]: pool = ThreadPool(8)

In [3]: x = np.arange(10)

In [4]: futures = pool.map(lambda x: x + 1, [x, x, x, x, x, x, x, x])

In [5]: wr = weakref.ref(x)

In [6]: sys.getrefcount(wr())
Out[6]: 3

In [7]: del futures

In [8]: sys.getrefcount(wr())
Out[8]: 3

In [9]: pool.close()

In [10]: sys.getrefcount(wr())
Out[10]: 2
```

cc @pitrou 

We could flush a few tasks through.  This seems a bit ugly though:

```python
In [14]: pool = ThreadPool(8)

In [15]: %time pool.map(lambda x: x, [None] * 8)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.67 ms
```

**Comment by pitrou** [comment]
This might be https://bugs.python.org/issue29861, in which case it would be fixed in the next bugfix releases of Python. Which version are you testing with?

**Comment by jcrist** [comment]
Flushing tasks has no effect for me. Here's an example working with just builtins.

```python
In [1]: import weakref, sys

In [2]: from multiprocessing.pool import ThreadPool

In [3]: p = ThreadPool()

In [4]: x = []

In [5]: sys.getrefcount(x)
Out[5]: 2

In [6]: p.apply(len, [x])
Out[6]: 0

In [7]: sys.getrefcount(x)
Out[7]: 3

In [8]: _ = p.map(lambda x: None, range(10000)) # flush lots of tasks

In [9]: sys.getrefcount(x)   # Still at 3 refs (one for getrefcount, one for x, one for pool)
Out[9]: 3

In [10]: import gc

In [11]: gc.collect(2)
Out[11]: 123

In [12]: sys.getrefcount(x)
Out[12]: 3

In [13]: p.close()

In [14]: sys.getrefcount(x)
Out[14]: 2

In [15]: sys.version_info
Out[15]: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by pitrou** [comment]
On Python git master:
```
>>> from multiprocessing.pool import ThreadPool
>>> p = ThreadPool()
>>> x = []
>>> import sys, weakref
>>> sys.getrefcount(x)
2
>>> p.apply(len, [x])
0
>>> sys.getrefcount(x)
2
```

**Comment by pitrou** [comment]
@jcrist, if you upgrade to 3.5.4, it should be fixed.

**Comment by pitrou** [comment]
Recommending users upgrade would be my recommendation.

**Comment by mrocklin** [comment]
Sounds good.  Closing as fixed upstream.

**Comment by jierice** [comment]
Upgrading does solve the problem above. But if I use `dask.distributed`, it will still have the same problem with the following code.
```
import numpy as np
import dask
import dask.array as da
import psutil

from dask.distributed import Client

if __name__ == '__main__':

   client = Client()

   print('case 3: \n')
   print('before create numpy array:\n')
   print(psutil.virtual_memory())
   
   data = np.random.rand(1000,1000,1000)

   print('after create numpy array:\n')
   print(psutil.virtual_memory())

   chunkdata = da.from_array(data,chunks=(200,200,950)).persist(get=dask.threaded.get)

   print('after create dask array:\n')
   print(psutil.virtual_memory())

   chunkdata = chunkdata.persist()

   print('after persist dask array:\n')
   print(psutil.virtual_memory())
   client.cancel(chunkdata)

   print('after cancel dask array:\n')
   print(psutil.virtual_memory())

   del(data)

   print('after delete numpy array:\n')
   print(psutil.virtual_memory())

   del(chunkdata)

   print('after delete chunk array:\n')
   print(psutil.virtual_memory())

```

The result is
```
case 3: 

before create numpy array:

svmem(total=135289647104, available=131464286208, percent=2.8, used=3448115200, free=126619103232, active=5657690112, inactive=1523830784, buffers=158695424, cached=5063733248, shared=31240192)
after create numpy array:

svmem(total=135289647104, available=123448066048, percent=8.8, used=11464089600, free=118602616832, active=13661364224, inactive=1524064256, buffers=158711808, cached=5064228864, shared=31485952)
after create dask array:

svmem(total=135289647104, available=123448193024, percent=8.8, used=11463962624, free=118602711040, active=13661634560, inactive=1524080640, buffers=158720000, cached=5064253440, shared=31485952)
after persist dask array:

svmem(total=135289647104, available=123448193024, percent=8.8, used=11463962624, free=118602711040, active=13661634560, inactive=1524080640, buffers=158720000, cached=5064253440, shared=31485952)
after cancel dask array:

svmem(total=135289647104, available=115412697088, percent=14.7, used=19499454464, free=110567202816, active=21679382528, inactive=1524105216, buffers=158728192, cached=5064261632, shared=31485952)
after delete numpy array:

svmem(total=135289647104, available=115410411520, percent=14.7, used=19501740032, free=110564917248, active=21679714304, inactive=1524105216, buffers=158728192, cached=5064261632, shared=31485952)
after delete chunk array:

svmem(total=135289647104, available=115410411520, percent=14.7, used=19501740032, free=110564917248, active=21681041408, inactive=1524105216, buffers=158728192, cached=5064261632, shared=31485952)

```

**Comment by pitrou** [comment]
`concurrent.futures.ThreadPoolExecutor` (which `distributed` uses) suffers from a similar problem which hasn't been fixed yet: https://bugs.python.org/issue27144

**Comment by jierice** [comment]
Thanks! Is there any workaround here to release the memory?

**Comment by pitrou** [comment]
Nothing that I know of.

**Comment by jcrist** [comment]
Not great, but you could provide your own pool and close it afterwards. Threadpools are fairly quick to startup and shutdown, so this might not be terrible.

```python
In [1]: import dask, dask.array as da

In [2]: from multiprocessing.pool import ThreadPool

In [3]: x = da.random.normal(size=(10000, 10000), chunks=(1000, 1000))

In [4]: res = x.mean(axis=1).sum()

In [5]: with ThreadPool() as pool, dask.set_options(pool=pool):
   ...:     o = res.compute()  # dask uses your pool, pool is closed after exiting context manager
```

You can also pass `pool=pool` to the call to compute instead of using `dask.set_options`, up to you.

**Comment by jierice** [comment]
@jcrist Thanks. I replace
```
   chunkdata = da.from_array(data,chunks=(200,200,950)).persist(get=dask.threaded.get)

```
with
```
   with ThreadPool() as pool, dask.set_options(pool=pool,get=dask.threaded.get):
        chunkdata = da.from_array(data,chunks=(200,200,950)).persist()

```
But I still get the same result. Still couldn't release the memory.

**Comment by jcrist** [comment]
Are you sure? You won't release `data`, but the pool won't hold on to a reference anymore since it's closed:

```python
In [1]: from multiprocessing.pool import ThreadPool

In [2]: import dask

In [3]: import dask.array as da, numpy as np, sys, weakref

In [4]: x = np.arange(1000)

In [5]: wr = weakref.ref(x)

In [6]: dx = da.from_array(x, chunks=10)

In [7]: del x

In [8]: sys.getrefcount(wr())  # 1 for `dx`, 1 for `getrefcount`
Out[8]: 2

In [9]: with ThreadPool() as pool, dask.set_options(pool=pool):
   ...:     res = dx.persist()
   ...:

In [10]: sys.getrefcount(wr())  # 100 chunks, 1 for `dx`, 1 for `getrefcount`
Out[10]: 102

In [11]: del res

In [12]: sys.getrefcount(wr())  # 1 for `dx`, 1 for `getrefcount`
Out[12]: 2
```

**Comment by jierice** [comment]
I guess it must be related to `dask.distributed`. If I don't use `Client`, it will work.

**Comment by jierice** [comment]
Run the scrip below, 
```
import dask.array as da, numpy as np, sys, weakref
from multiprocessing.pool import ThreadPool
import dask
from dask.distributed import Client


if __name__ == '__main__':

  client=Client()
  x = np.arange(1000)
  wr = weakref.ref(x)
  dx = da.from_array(x,chunks=10)
  del x
  print(sys.getrefcount(wr()))
  with ThreadPool() as pool, dask.set_options(pool=pool,get=dask.threaded.get):
       res = dx.persist()
  res = res.persist()
  print(sys.getrefcount(wr()))
  client.cancel(res)
  del res
  print(sys.getrefcount(wr()))
```
I get 
```
2
102
102
```

**Comment by jcrist** [comment]
You're mixing schedulers here. Specifying pool only works on the local scheduler (threaded or multiprocessing). The call to `res.persist()` outside the context manager uses the distributed scheduler, which still has this issue as @pitrou pointed out. The call in the context manager uses the threaded scheduler (and then closes the pool), which does fix the issue. The fix mentioned above only works for the local schedulers (threaded or multiprocessing).

**Comment by jierice** [comment]
Thanks. The reason I do this is because I have a large `numpy` array,  I want to `persist` in the `distributed ` processors. So I chunk it locally first and then `persist`.  I found even I close the `client`, the `refcount` here is still `102`.

**Comment by jcrist** [comment]
Hmmm, I'm not sure where distributed is holding on to a reference here. @mrocklin, thoughts? I'd expect dropping all references to the pre-persisted graph to remove the initial data from the client process.

```python
In [1]: from dask.distributed import Client

In [2]: client = Client('tcp://10.10.20.42:8786')

In [3]: client.restart()
distributed.client - INFO - Receive restart signal from scheduler
Out[3]: <Client: scheduler='tcp://10.10.20.42:8786' processes=1 cores=8>

In [4]: import dask.array as da, numpy as np

In [5]: import sys, weakref

In [6]: x = np.arange(1000)

In [7]: dx = da.from_array(x, chunks=1000)

In [8]: wr = weakref.ref(x)

In [9]: del x

In [10]: sys.getrefcount(wr())
Out[10]: 2

In [11]: res = dx.persist()

In [12]: sys.getrefcount(wr())
Out[12]: 3

In [13]: del dx

In [14]: sys.getrefcount(wr())  # still have a reference to the original data somewhere
Out[14]: 2

In [15]: dict(res.dask)  # no reference to x in the graph
Out[15]:
{('array-b5a83eb375106ee782d8c9e6c51e4d9d',
  0): <Future: status: finished, type: ndarray, key: ('array-b5a83eb375106ee782d8c9e6c51e4d9d', 0)>}
```

---

> The reason I do this is because I have a large numpy array, I want to persist in the distributed processors.

Note that for larger data it's recommended to have the workers load the data if possible. I still consider the lingering refcount here a bug though (unless @mrocklin thinks otherwise), thanks for reporting it.

**Comment by jierice** [comment]
@jcrist I didn't use worker to load the data because the data is larger than the memory of a single processor. So I have to load the data first and distribute it.

**Comment by mrocklin** [comment]
@jcrist the array is in `cluster.scheduler_comm.recent_message_log`

We should probably avoid storing large results in that log by default.  This could be done either by setting its size to zero by default (increasing it only for debugging situations) or by tracking the number of bytes sent in a message and only storing those messages with a small number of bytes.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/1361

**Comment by mrocklin** [comment]
@jierice I don't see how the code above would cause a 30GB leak.  

Some general notes:

1.  The threadpool and set_options code doesn't do anything at the moment because you have a distributed scheduler active, which is serving as the default scheduler.  
2.  Likewise your second persist call won't do much
3.  You should avoid sending large data through the scheduler.  See this new stack overflow question and answer, which will hopefully clear some things up: https://stackoverflow.com/questions/45941528/how-to-efficiently-send-a-large-numpy-array-to-the-cluster-with-dask-array/45941529#45941529

**Comment by jakirkham** [comment]
> `concurrent.futures.ThreadPoolExecutor` (which `distributed` uses) suffers from a similar problem which hasn't been fixed yet: https://bugs.python.org/issue27144

Just an FYI, this part of the issue appears to have been fixed in Python 3.6+.

**Comment by jakirkham** [comment]
AFAICT both upstream issues have been addressed in CPython and should be in any Python 3.8+, which are supported (though looks like earlier versions too).

The last example needs some changes (as already noted above). Though even making these locally am not seeing the ramp up in memory usage (not to say there couldn't be cases like this).

Going to go ahead and close. Though please feel free to share anything else encountered in a new issue. Thanks! 🙏
