### ISSUE TITLE
Change index.dtype

### ISSUE THREAD

**Issue by MMAThijssen** [dask/dask#4730]
Hi, 

The dtype of the index changes from datetime64[ns] to int after executing map_partitions.
 ``` data[COLUMN_A] = data[COLUMN_A].map_partitions(butterworth_filter, frequency, critical_frequency, order, meta=a_dtype)```

Next, I want to do a groupby which requires DatetimeIndex, TimedeltaInda or PeriodIndex, while I know have a RangeIndex. 

Trying to change the dtype using ```data.index = data.index.astype(index_dtype)``` in which index_type = datetime64[ns], gives an AttributeError (can't set attribute). Anyways, it seems to be an undesired effect from map_partitions. How to correct this?

**Comment by jcrist** [comment]
What version of Dask are you using? From your description it sounds like the metadata of `data` is inferred incorrectly after:

```python
data[COLUMN_A] = data[COLUMN_A].map_partitions(butterworth_filter, frequency, critical_frequency, order, meta=a_dtype)
```

it doesn't look like you're modifying the index of `data`, but you say it changes to `int`. This was a bug in previous versions, but should be fixed in the latest release (1.2.0). Here I try to do a similar operation to demonstrate the bug, but the index dtype is unchanged.

```python
In [1]: import dask.dataframe as dd

In [2]: from dask.datasets import timeseries

In [3]: ddf = timeseries()

In [4]: ddf.dtypes
Out[4]:
id        int64
name     object
x       float64
y       float64
dtype: object

In [5]: ddf.index.dtype
Out[5]: dtype('<M8[ns]')

In [6]: ddf['x'] = ddf.x.map_partitions(lambda x: x + 1, meta=ddf.x.dtype)

In [7]: ddf.index.dtype
Out[7]: dtype('<M8[ns]')

In [8]: ddf.head()
Out[8]:
                       id     name         x         y
timestamp
2000-01-01 00:00:00  1026    Frank  0.192276  0.014399
2000-01-01 00:00:01   999   Hannah  0.315094  0.442208
2000-01-01 00:00:02  1034  Norbert  1.252921 -0.188687
2000-01-01 00:00:03  1073    Quinn  1.220467  0.981420
2000-01-01 00:00:04   981   Yvonne  0.835776  0.412051
```

If you still have issues, can you provide a reproducible example (https://blog.dask.org/2018/02/28/minimal-bug-reports).

**Comment by MMAThijssen** [comment]
Thank you for your reply!

I updated Dask from 1.1.4 to 1.2.0. However, if I reproduce your example, the dtype of the index is still converted from datetime64[ns] to int64. The bug doesn't seem to be fixed.

**Comment by jcrist** [comment]
What version of Pandas are you using? I can't remember what version, but some older version of pandas has a bug where empty indices are ignored when setting the index type (which breaks our metadata handling). This does work with Pandas 0.24.2.

**Comment by MMAThijssen** [comment]
I am also working with Pandas 0.24.2, so I do not get why I still get the error. I have decided to continue on without Dask.

**Comment by jcrist** [comment]
I'm sorry to hear that, hopefully dask can still be of use to you in the future. Since we're unable to reproduce this error locally, I'm going to close this issue. Feel free to reopen if you're still interested in resolving it.

**Comment by MMAThijssen** [comment]
It seems like I do need to use Dask, so I am looking into this problem again. I am working with Python version 3.7. I created a virtual environment to check functionality, but the issue is still present.

To be clear, these are the installed packages in the venv.

```
In [1]: pip freeze

Out [2]: 
cloudpickle==0.8.1
dask==1.2.0
locket==0.2.0
numpy==1.16.3
pandas==0.24.2
partd==0.3.10
python-dateutil==2.8.0
pytz==2019.1
six==1.12.0
toolz==0.9.0
```

I checked and these are all the latest versions of the packages. I still get the exact same result when trying your examples: index.dtype is converted from ```<M8[ns]``` to ```int64```.
