### ISSUE TITLE
test_parquet.py::test_select_filtered_column[fastparquet]: pandas backend fails to filter NoneType

### ISSUE THREAD

**Issue by bnavigator** [dask/dask#9975]
**Describe the issue**:

Since the update to fastparquet 2023.2.0, the test suite fails with the following error while building packages for openSUSE:

```
[  260s] E           TypeError: An error occurred while calling the read_parquet method registered to the pandas backend.
[  260s] E           Original Message: '<=' not supported between instances of 'NoneType' and 'str'
...
[  260s] FAILED dataframe/io/tests/test_parquet.py::test_select_filtered_column[fastparquet]
```

<details>

```python
[  260s] =================================== FAILURES ===================================
[  260s] ___________________ test_select_filtered_column[fastparquet] ___________________
[  260s] [gw5] linux -- Python 3.10.9 /usr/bin/python3.10
[  260s] 
[  260s] args = (PosixPath('/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3/test_select_filtered_column.parquet'),)
[  260s] kwargs = {'engine': 'fastparquet', 'filters': [('b', '==', 'cat')]}
[  260s] func = <function read_parquet at 0x7f266697f9a0>
[  260s] 
[  260s]     @wraps(fn)
[  260s]     def wrapper(*args, **kwargs):
[  260s]         func = getattr(self, dispatch_name)
[  260s]         try:
[  260s] >           return func(*args, **kwargs)
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/backends.py:133: 
[  260s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  260s] 
[  260s] path = '/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3/test_select_filtered_column.parquet'
[  260s] columns = None, filters = [('b', '==', 'cat')], categories = None, index = None
[  260s] storage_options = None
[  260s] engine = <class 'dask.dataframe.io.parquet.fastparquet.FastParquetEngine'>
[  260s] use_nullable_dtypes = False, calculate_divisions = False
[  260s] ignore_metadata_file = False, metadata_task_size = None
[  260s] split_row_groups = False, chunksize = None, aggregate_files = None
[  260s] parquet_file_extension = ('.parq', '.parquet', '.pq'), filesystem = None
[  260s] kwargs = {}
[  260s] input_kwargs = {'aggregate_files': None, 'calculate_divisions': False, 'categories': None, 'chunksize': None, ...}
[  260s] dataset_options = {}, read_options = {'open_file_options': {}}
[  260s] open_file_options = {}, other_options = {}
[  260s] fs = <fsspec.implementations.local.LocalFileSystem object at 0x7f2660742530>
[  260s] 
[  260s]     @dataframe_creation_dispatch.register_inplace("pandas")
[  260s]     def read_parquet(
[  260s]         path,
[  260s]         columns=None,
[  260s]         filters=None,
[  260s]         categories=None,
[  260s]         index=None,
[  260s]         storage_options=None,
[  260s]         engine="auto",
[  260s]         use_nullable_dtypes: bool = False,
[  260s]         calculate_divisions=None,
[  260s]         ignore_metadata_file=False,
[  260s]         metadata_task_size=None,
[  260s]         split_row_groups=False,
[  260s]         chunksize=None,
[  260s]         aggregate_files=None,
[  260s]         parquet_file_extension=(".parq", ".parquet", ".pq"),
[  260s]         filesystem=None,
[  260s]         **kwargs,
[  260s]     ):
[  260s]         """
[  260s]         Read a Parquet file into a Dask DataFrame
[  260s]     
[  260s]         This reads a directory of Parquet data into a Dask.dataframe, one file per
[  260s]         partition.  It selects the index among the sorted columns if any exist.
[  260s]     
[  260s]         Parameters
[  260s]         ----------
[  260s]         path : str or list
[  260s]             Source directory for data, or path(s) to individual parquet files.
[  260s]             Prefix with a protocol like ``s3://`` to read from alternative
[  260s]             filesystems. To read from multiple files you can pass a globstring or a
[  260s]             list of paths, with the caveat that they must all have the same
[  260s]             protocol.
[  260s]         columns : str or list, default None
[  260s]             Field name(s) to read in as columns in the output. By default all
[  260s]             non-index fields will be read (as determined by the pandas parquet
[  260s]             metadata, if present). Provide a single field name instead of a list to
[  260s]             read in the data as a Series.
[  260s]         filters : Union[List[Tuple[str, str, Any]], List[List[Tuple[str, str, Any]]]], default None
[  260s]             List of filters to apply, like ``[[('col1', '==', 0), ...], ...]``.
[  260s]             Using this argument will NOT result in row-wise filtering of the final
[  260s]             partitions unless ``engine="pyarrow"`` is also specified.  For
[  260s]             other engines, filtering is only performed at the partition level, that is,
[  260s]             to prevent the loading of some row-groups and/or files.
[  260s]     
[  260s]             For the "pyarrow" engine, predicates can be expressed in disjunctive
[  260s]             normal form (DNF). This means that the inner-most tuple describes a single
[  260s]             column predicate. These inner predicates are combined with an AND
[  260s]             conjunction into a larger predicate. The outer-most list then combines all
[  260s]             of the combined filters with an OR disjunction.
[  260s]     
[  260s]             Predicates can also be expressed as a ``List[Tuple]``. These are evaluated
[  260s]             as an AND conjunction. To express OR in predicates, one must use the
[  260s]             (preferred for "pyarrow") ``List[List[Tuple]]`` notation.
[  260s]     
[  260s]             Note that the "fastparquet" engine does not currently support DNF for
[  260s]             the filtering of partitioned columns (``List[Tuple]`` is required).
[  260s]         index : str, list or False, default None
[  260s]             Field name(s) to use as the output frame index. By default will be
[  260s]             inferred from the pandas parquet file metadata, if present. Use ``False``
[  260s]             to read all fields as columns.
[  260s]         categories : list or dict, default None
[  260s]             For any fields listed here, if the parquet encoding is Dictionary,
[  260s]             the column will be created with dtype category. Use only if it is
[  260s]             guaranteed that the column is encoded as dictionary in all row-groups.
[  260s]             If a list, assumes up to 2**16-1 labels; if a dict, specify the number
[  260s]             of labels expected; if None, will load categories automatically for
[  260s]             data written by dask/fastparquet, not otherwise.
[  260s]         storage_options : dict, default None
[  260s]             Key/value pairs to be passed on to the file-system backend, if any.
[  260s]             Note that the default file-system backend can be configured with the
[  260s]             ``filesystem`` argument, described below.
[  260s]         open_file_options : dict, default None
[  260s]             Key/value arguments to be passed along to ``AbstractFileSystem.open``
[  260s]             when each parquet data file is open for reading. Experimental
[  260s]             (optimized) "precaching" for remote file systems (e.g. S3, GCS) can
[  260s]             be enabled by adding ``{"method": "parquet"}`` under the
[  260s]             ``"precache_options"`` key. Also, a custom file-open function can be
[  260s]             used (instead of ``AbstractFileSystem.open``), by specifying the
[  260s]             desired function under the ``"open_file_func"`` key.
[  260s]         engine : {'auto', 'pyarrow', 'fastparquet'}, default 'auto'
[  260s]             Parquet library to use. Defaults to 'auto', which uses ``pyarrow`` if
[  260s]             it is installed, and falls back to ``fastparquet`` otherwise.
[  260s]         use_nullable_dtypes : {False, True}
[  260s]             Whether to use extension dtypes for the resulting ``DataFrame``.
[  260s]             ``use_nullable_dtypes=True`` is only supported when ``engine="pyarrow"``.
[  260s]     
[  260s]             .. note::
[  260s]     
[  260s]                 Use the ``dataframe.dtype_backend`` config option to select which
[  260s]                 dtype implementation to use.
[  260s]     
[  260s]                 ``dataframe.dtype_backend="pandas"`` (the default) will use
[  260s]                 pandas' ``numpy``-backed nullable dtypes (e.g. ``Int64``,
[  260s]                 ``string[python]``, etc.) while ``dataframe.dtype_backend="pyarrow"``
[  260s]                 will use ``pyarrow``-backed extension dtypes (e.g. ``int64[pyarrow]``,
[  260s]                 ``string[pyarrow]``, etc.). ``dataframe.dtype_backend="pyarrow"``
[  260s]                 requires ``pandas`` 1.5+.
[  260s]     
[  260s]         calculate_divisions : bool, default False
[  260s]             Whether to use min/max statistics from the footer metadata (or global
[  260s]             ``_metadata`` file) to calculate divisions for the output DataFrame
[  260s]             collection. Divisions will not be calculated if statistics are missing.
[  260s]             This option will be ignored if ``index`` is not specified and there is
[  260s]             no physical index column specified in the custom "pandas" Parquet
[  260s]             metadata. Note that ``calculate_divisions=True`` may be extremely slow
[  260s]             when no global ``_metadata`` file is present, especially when reading
[  260s]             from remote storage. Set this to ``True`` only when known divisions
[  260s]             are needed for your workload (see :ref:`dataframe-design-partitions`).
[  260s]         ignore_metadata_file : bool, default False
[  260s]             Whether to ignore the global ``_metadata`` file (when one is present).
[  260s]             If ``True``, or if the global ``_metadata`` file is missing, the parquet
[  260s]             metadata may be gathered and processed in parallel. Parallel metadata
[  260s]             processing is currently supported for ``ArrowDatasetEngine`` only.
[  260s]         metadata_task_size : int, default configurable
[  260s]             If parquet metadata is processed in parallel (see ``ignore_metadata_file``
[  260s]             description above), this argument can be used to specify the number of
[  260s]             dataset files to be processed by each task in the Dask graph.  If this
[  260s]             argument is set to ``0``, parallel metadata processing will be disabled.
[  260s]             The default values for local and remote filesystems can be specified
[  260s]             with the "metadata-task-size-local" and "metadata-task-size-remote"
[  260s]             config fields, respectively (see "dataframe.parquet").
[  260s]         split_row_groups : bool or int, default False
[  260s]             If True, then each output dataframe partition will correspond to a single
[  260s]             parquet-file row-group. If False, each partition will correspond to a
[  260s]             complete file.  If a positive integer value is given, each dataframe
[  260s]             partition will correspond to that number of parquet row-groups (or fewer).
[  260s]         chunksize : int or str, default None
[  260s]             WARNING: The ``chunksize`` argument will be deprecated in the future.
[  260s]             Please use ``split_row_groups`` to specify how many row-groups should be
[  260s]             mapped to each output partition. If you strongly oppose the deprecation of
[  260s]             ``chunksize``, please comment at https://github.com/dask/dask/issues/9043".
[  260s]     
[  260s]             The desired size of each output ``DataFrame`` partition in terms of total
[  260s]             (uncompressed) parquet storage space. If specified, adjacent row-groups
[  260s]             and/or files will be aggregated into the same output partition until the
[  260s]             cumulative ``total_byte_size`` parquet-metadata statistic reaches this
[  260s]             value. Use `aggregate_files` to enable/disable inter-file aggregation.
[  260s]         aggregate_files : bool or str, default None
[  260s]             WARNING: The ``aggregate_files`` argument will be deprecated in the future.
[  260s]             Please consider using ``from_map`` to create a DataFrame collection with a
[  260s]             custom file-to-partition mapping. If you strongly oppose the deprecation of
[  260s]             ``aggregate_files``, comment at https://github.com/dask/dask/issues/9051".
[  260s]     
[  260s]             Whether distinct file paths may be aggregated into the same output
[  260s]             partition. This parameter is only used when `chunksize` is specified
[  260s]             or when `split_row_groups` is an integer >1. A setting of True means
[  260s]             that any two file paths may be aggregated into the same output partition,
[  260s]             while False means that inter-file aggregation is prohibited.
[  260s]     
[  260s]             For "hive-partitioned" datasets, a "partition"-column name can also be
[  260s]             specified. In this case, we allow the aggregation of any two files
[  260s]             sharing a file path up to, and including, the corresponding directory name.
[  260s]             For example, if ``aggregate_files`` is set to ``"section"`` for the
[  260s]             directory structure below, ``03.parquet`` and ``04.parquet`` may be
[  260s]             aggregated together, but ``01.parquet`` and ``02.parquet`` cannot be.
[  260s]             If, however, ``aggregate_files`` is set to ``"region"``, ``01.parquet``
[  260s]             may be aggregated with ``02.parquet``, and ``03.parquet`` may be aggregated
[  260s]             with ``04.parquet``::
[  260s]     
[  260s]                 dataset-path/
[  260s]                 ├── region=1/
[  260s]                 │   ├── section=a/
[  260s]                 │   │   └── 01.parquet
[  260s]                 │   ├── section=b/
[  260s]                 │   └── └── 02.parquet
[  260s]                 └── region=2/
[  260s]                     ├── section=a/
[  260s]                     │   ├── 03.parquet
[  260s]                     └── └── 04.parquet
[  260s]     
[  260s]             Note that the default behavior of ``aggregate_files`` is ``False``.
[  260s]         parquet_file_extension: str, tuple[str], or None, default (".parq", ".parquet", ".pq")
[  260s]             A file extension or an iterable of extensions to use when discovering
[  260s]             parquet files in a directory. Files that don't match these extensions
[  260s]             will be ignored. This argument only applies when ``paths`` corresponds
[  260s]             to a directory and no ``_metadata`` file is present (or
[  260s]             ``ignore_metadata_file=True``). Passing in ``parquet_file_extension=None``
[  260s]             will treat all files in the directory as parquet files.
[  260s]     
[  260s]             The purpose of this argument is to ensure that the engine will ignore
[  260s]             unsupported metadata files (like Spark's '_SUCCESS' and 'crc' files).
[  260s]             It may be necessary to change this argument if the data files in your
[  260s]             parquet dataset do not end in ".parq", ".parquet", or ".pq".
[  260s]         filesystem: "fsspec", "arrow", fsspec.AbstractFileSystem, or pyarrow.fs.FileSystem
[  260s]             Filesystem backend to use. Note that the "fastparquet" engine only
[  260s]             supports "fsspec" or an explicit ``pyarrow.fs.FileSystem`` object.
[  260s]             Default is "fsspec".
[  260s]         dataset: dict, default None
[  260s]             Dictionary of options to use when creating a ``pyarrow.dataset.Dataset``
[  260s]             or ``fastparquet.ParquetFile`` object. These options may include a
[  260s]             "filesystem" key (or "fs" for the "fastparquet" engine) to configure
[  260s]             the desired file-system backend. However, the top-level ``filesystem``
[  260s]             argument will always take precedence.
[  260s]         read: dict, default None
[  260s]             Dictionary of options to pass through to ``engine.read_partitions``
[  260s]             using the ``read`` key-word argument.
[  260s]         arrow_to_pandas: dict, default None
[  260s]             Dictionary of options to use when converting from ``pyarrow.Table`` to
[  260s]             a pandas ``DataFrame`` object. Only used by the "arrow" engine.
[  260s]         **kwargs: dict (of dicts)
[  260s]             Options to pass through to ``engine.read_partitions`` as stand-alone
[  260s]             key-word arguments. Note that these options will be ignored by the
[  260s]             engines defined in ``dask.dataframe``, but may be used by other custom
[  260s]             implementations.
[  260s]     
[  260s]         Examples
[  260s]         --------
[  260s]         >>> df = dd.read_parquet('s3://bucket/my-parquet-data')  # doctest: +SKIP
[  260s]     
[  260s]         See Also
[  260s]         --------
[  260s]         to_parquet
[  260s]         pyarrow.parquet.ParquetDataset
[  260s]         """
[  260s]     
[  260s]         if use_nullable_dtypes:
[  260s]             use_nullable_dtypes = dask.config.get("dataframe.dtype_backend")
[  260s]     
[  260s]         # "Pre-deprecation" warning for `chunksize`
[  260s]         if chunksize:
[  260s]             warnings.warn(
[  260s]                 "The `chunksize` argument will be deprecated in the future. "
[  260s]                 "Please use `split_row_groups` to specify how many row-groups "
[  260s]                 "should be mapped to each output partition.\n\n"
[  260s]                 "If you strongly oppose the deprecation of `chunksize`, please "
[  260s]                 "comment at https://github.com/dask/dask/issues/9043",
[  260s]                 FutureWarning,
[  260s]             )
[  260s]     
[  260s]         # "Pre-deprecation" warning for `aggregate_files`
[  260s]         if aggregate_files:
[  260s]             warnings.warn(
[  260s]                 "The `aggregate_files` argument will be deprecated in the future. "
[  260s]                 "Please consider using `from_map` to create a DataFrame collection "
[  260s]                 "with a custom file-to-partition mapping.\n\n"
[  260s]                 "If you strongly oppose the deprecation of `aggregate_files`, "
[  260s]                 "please comment at https://github.com/dask/dask/issues/9051",
[  260s]                 FutureWarning,
[  260s]             )
[  260s]     
[  260s]         if "read_from_paths" in kwargs:
[  260s]             kwargs.pop("read_from_paths")
[  260s]             warnings.warn(
[  260s]                 "`read_from_paths` is no longer supported and will be ignored.",
[  260s]                 FutureWarning,
[  260s]             )
[  260s]     
[  260s]         # Handle gather_statistics deprecation
[  260s]         if "gather_statistics" in kwargs:
[  260s]             if calculate_divisions is None:
[  260s]                 calculate_divisions = kwargs.pop("gather_statistics")
[  260s]                 warnings.warn(
[  260s]                     "``gather_statistics`` is deprecated and will be removed in a "
[  260s]                     "future release. Please use ``calculate_divisions`` instead.",
[  260s]                     FutureWarning,
[  260s]                 )
[  260s]             else:
[  260s]                 warnings.warn(
[  260s]                     f"``gather_statistics`` is deprecated. Ignoring this option "
[  260s]                     f"in favor of ``calculate_divisions={calculate_divisions}``",
[  260s]                     FutureWarning,
[  260s]                 )
[  260s]         calculate_divisions = bool(calculate_divisions)
[  260s]     
[  260s]         # We support a top-level `parquet_file_extension` kwarg, but
[  260s]         # must check if the deprecated `require_extension` option is
[  260s]         # being passed to the engine. If `parquet_file_extension` is
[  260s]         # set to the default value, and `require_extension` was also
[  260s]         # specified, we will use `require_extension` but warn the user.
[  260s]         if (
[  260s]             "dataset" in kwargs
[  260s]             and "require_extension" in kwargs["dataset"]
[  260s]             and parquet_file_extension == (".parq", ".parquet", ".pq")
[  260s]         ):
[  260s]             parquet_file_extension = kwargs["dataset"].pop("require_extension")
[  260s]             warnings.warn(
[  260s]                 "require_extension is deprecated, and will be removed from "
[  260s]                 "read_parquet in a future release. Please use the top-level "
[  260s]                 "parquet_file_extension argument instead.",
[  260s]                 FutureWarning,
[  260s]             )
[  260s]     
[  260s]         # Store initial function arguments
[  260s]         input_kwargs = {
[  260s]             "columns": columns,
[  260s]             "filters": filters,
[  260s]             "categories": categories,
[  260s]             "index": index,
[  260s]             "storage_options": storage_options,
[  260s]             "engine": engine,
[  260s]             "use_nullable_dtypes": use_nullable_dtypes,
[  260s]             "calculate_divisions": calculate_divisions,
[  260s]             "ignore_metadata_file": ignore_metadata_file,
[  260s]             "metadata_task_size": metadata_task_size,
[  260s]             "split_row_groups": split_row_groups,
[  260s]             "chunksize": chunksize,
[  260s]             "aggregate_files": aggregate_files,
[  260s]             "parquet_file_extension": parquet_file_extension,
[  260s]             "filesystem": filesystem,
[  260s]             **kwargs,
[  260s]         }
[  260s]     
[  260s]         if isinstance(columns, str):
[  260s]             input_kwargs["columns"] = [columns]
[  260s]             df = read_parquet(path, **input_kwargs)
[  260s]             return df[columns]
[  260s]     
[  260s]         if columns is not None:
[  260s]             columns = list(columns)
[  260s]     
[  260s]         if isinstance(engine, str):
[  260s]             engine = get_engine(engine)
[  260s]     
[  260s]         if hasattr(path, "name"):
[  260s]             path = stringify_path(path)
[  260s]     
[  260s]         # Update input_kwargs
[  260s]         input_kwargs.update({"columns": columns, "engine": engine})
[  260s]     
[  260s]         # Process and split user options
[  260s]         (
[  260s]             dataset_options,
[  260s]             read_options,
[  260s]             open_file_options,
[  260s]             other_options,
[  260s]         ) = _split_user_options(**kwargs)
[  260s]     
[  260s]         # Extract global filesystem and paths
[  260s]         fs, paths, dataset_options, open_file_options = engine.extract_filesystem(
[  260s]             path,
[  260s]             filesystem,
[  260s]             dataset_options,
[  260s]             open_file_options,
[  260s]             storage_options,
[  260s]         )
[  260s]         read_options["open_file_options"] = open_file_options
[  260s]         paths = sorted(paths, key=natural_sort_key)  # numeric rather than glob ordering
[  260s]     
[  260s]         auto_index_allowed = False
[  260s]         if index is None:
[  260s]             # User is allowing auto-detected index
[  260s]             auto_index_allowed = True
[  260s]         if index and isinstance(index, str):
[  260s]             index = [index]
[  260s]     
[  260s]         read_metadata_result = engine.read_metadata(
[  260s]             fs,
[  260s]             paths,
[  260s]             categories=categories,
[  260s]             index=index,
[  260s]             use_nullable_dtypes=use_nullable_dtypes,
[  260s]             gather_statistics=calculate_divisions,
[  260s]             filters=filters,
[  260s]             split_row_groups=split_row_groups,
[  260s]             chunksize=chunksize,
[  260s]             aggregate_files=aggregate_files,
[  260s]             ignore_metadata_file=ignore_metadata_file,
[  260s]             metadata_task_size=metadata_task_size,
[  260s]             parquet_file_extension=parquet_file_extension,
[  260s]             dataset=dataset_options,
[  260s]             read=read_options,
[  260s]             **other_options,
[  260s]         )
[  260s]     
[  260s]         # In the future, we may want to give the engine the
[  260s]         # option to return a dedicated element for `common_kwargs`.
[  260s]         # However, to avoid breaking the API, we just embed this
[  260s]         # data in the first element of `parts` for now.
[  260s]         # The logic below is inteded to handle backward and forward
[  260s]         # compatibility with a user-defined engine.
[  260s]         meta, statistics, parts, index = read_metadata_result[:4]
[  260s]         common_kwargs = {}
[  260s]         aggregation_depth = False
[  260s]         if len(parts):
[  260s]             # For now, `common_kwargs` and `aggregation_depth`
[  260s]             # may be stored in the first element of `parts`
[  260s]             common_kwargs = parts[0].pop("common_kwargs", {})
[  260s]             aggregation_depth = parts[0].pop("aggregation_depth", aggregation_depth)
[  260s]     
[  260s]         # Parse dataset statistics from metadata (if available)
[  260s] >       parts, divisions, index = process_statistics(
[  260s]             parts,
[  260s]             statistics,
[  260s]             filters,
[  260s]             index,
[  260s]             chunksize,
[  260s]             split_row_groups,
[  260s]             fs,
[  260s]             aggregation_depth,
[  260s]         )
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:565: 
[  260s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  260s] 
[  260s] parts = ({'piece': ('/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3/test_select_filtered_column.parquet', [0])},)
[  260s] statistics = ({'columns': [{'max': None, 'min': None, 'name': 'b'}], 'file_path_0': 'test_select_filtered_column.parquet', 'num-row-groups': 1, 'num-rows': 10, ...},)
[  260s] filters = [('b', '==', 'cat')], index = None, chunksize = None
[  260s] split_row_groups = False
[  260s] fs = <fsspec.implementations.local.LocalFileSystem object at 0x7f2660742530>
[  260s] aggregation_depth = None
[  260s] 
[  260s]     def process_statistics(
[  260s]         parts,
[  260s]         statistics,
[  260s]         filters,
[  260s]         index,
[  260s]         chunksize,
[  260s]         split_row_groups,
[  260s]         fs,
[  260s]         aggregation_depth,
[  260s]     ):
[  260s]         """Process row-group column statistics in metadata
[  260s]         Used in read_parquet.
[  260s]         """
[  260s]         if statistics and len(parts) != len(statistics):
[  260s]             # It is up to the Engine to guarantee that these
[  260s]             # lists are the same length (if statistics are defined).
[  260s]             # This misalignment may be indicative of a bug or
[  260s]             # incorrect read_parquet usage, so throw a warning.
[  260s]             warnings.warn(
[  260s]                 f"Length of partition statistics ({len(statistics)}) "
[  260s]                 f"does not match the partition count ({len(parts)}). "
[  260s]                 f"This may indicate a bug or incorrect read_parquet "
[  260s]                 f"usage. We must ignore the statistics and disable: "
[  260s]                 f"filtering, divisions, and/or file aggregation."
[  260s]             )
[  260s]             statistics = []
[  260s]     
[  260s]         divisions = None
[  260s]         if statistics:
[  260s]             result = list(
[  260s]                 zip(
[  260s]                     *[
[  260s]                         (part, stats)
[  260s]                         for part, stats in zip(parts, statistics)
[  260s]                         if stats["num-rows"] > 0
[  260s]                     ]
[  260s]                 )
[  260s]             )
[  260s]             parts, statistics = result or [[], []]
[  260s]             if filters:
[  260s] >               parts, statistics = apply_filters(parts, statistics, filters)
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:1426: 
[  260s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  260s] 
[  260s] parts = ({'piece': ('/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3/test_select_filtered_column.parquet', [0])},)
[  260s] statistics = ({'columns': [{'max': None, 'min': None, 'name': 'b'}], 'file_path_0': 'test_select_filtered_column.parquet', 'num-row-groups': 1, 'num-rows': 10, ...},)
[  260s] filters = [('b', '==', 'cat')]
[  260s] 
[  260s]     def apply_filters(parts, statistics, filters):
[  260s]         """Apply filters onto parts/statistics pairs
[  260s]     
[  260s]         Parameters
[  260s]         ----------
[  260s]         parts: list
[  260s]             Tokens corresponding to row groups to read in the future
[  260s]         statistics: List[dict]
[  260s]             List of statistics for each part, including min and max values
[  260s]         filters: Union[List[Tuple[str, str, Any]], List[List[Tuple[str, str, Any]]]]
[  260s]             List of filters to apply, like ``[[('x', '=', 0), ...], ...]``. This
[  260s]             implements partition-level (hive) filtering only, i.e., to prevent the
[  260s]             loading of some row-groups and/or files.
[  260s]     
[  260s]             Predicates can be expressed in disjunctive normal form (DNF). This means
[  260s]             that the innermost tuple describes a single column predicate. These
[  260s]             inner predicates are combined with an AND conjunction into a larger
[  260s]             predicate. The outer-most list then combines all of the combined
[  260s]             filters with an OR disjunction.
[  260s]     
[  260s]             Predicates can also be expressed as a List[Tuple]. These are evaluated
[  260s]             as an AND conjunction. To express OR in predicates, one must use the
[  260s]             (preferred) List[List[Tuple]] notation.
[  260s]     
[  260s]             Note that the "fastparquet" engine does not currently support DNF for
[  260s]             the filtering of partitioned columns (List[Tuple] is required).
[  260s]         Returns
[  260s]         -------
[  260s]         parts, statistics: the same as the input, but possibly a subset
[  260s]         """
[  260s]     
[  260s]         def apply_conjunction(parts, statistics, conjunction):
[  260s]             for column, operator, value in conjunction:
[  260s]                 if operator == "in" and not isinstance(value, (list, set, tuple)):
[  260s]                     raise TypeError("Value of 'in' filter must be a list, set, or tuple.")
[  260s]                 out_parts = []
[  260s]                 out_statistics = []
[  260s]                 for part, stats in zip(parts, statistics):
[  260s]                     if "filter" in stats and stats["filter"]:
[  260s]                         continue  # Filtered by engine
[  260s]                     try:
[  260s]                         c = toolz.groupby("name", stats["columns"])[column][0]
[  260s]                         min = c["min"]
[  260s]                         max = c["max"]
[  260s]                     except KeyError:
[  260s]                         out_parts.append(part)
[  260s]                         out_statistics.append(stats)
[  260s]                     else:
[  260s]                         if (
[  260s]                             operator in ("==", "=")
[  260s]                             and min <= value <= max
[  260s]                             or operator == "!="
[  260s]                             and (min != value or max != value)
[  260s]                             or operator == "<"
[  260s]                             and min < value
[  260s]                             or operator == "<="
[  260s]                             and min <= value
[  260s]                             or operator == ">"
[  260s]                             and max > value
[  260s]                             or operator == ">="
[  260s]                             and max >= value
[  260s]                             or operator == "in"
[  260s]                             and any(min <= item <= max for item in value)
[  260s]                         ):
[  260s]                             out_parts.append(part)
[  260s]                             out_statistics.append(stats)
[  260s]     
[  260s]                 parts, statistics = out_parts, out_statistics
[  260s]     
[  260s]             return parts, statistics
[  260s]     
[  260s]         conjunction, *disjunction = filters if isinstance(filters[0], list) else [filters]
[  260s]     
[  260s] >       out_parts, out_statistics = apply_conjunction(parts, statistics, conjunction)
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:1376: 
[  260s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  260s] 
[  260s] parts = ({'piece': ('/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3/test_select_filtered_column.parquet', [0])},)
[  260s] statistics = ({'columns': [{'max': None, 'min': None, 'name': 'b'}], 'file_path_0': 'test_select_filtered_column.parquet', 'num-row-groups': 1, 'num-rows': 10, ...},)
[  260s] conjunction = [('b', '==', 'cat')]
[  260s] 
[  260s]     def apply_conjunction(parts, statistics, conjunction):
[  260s]         for column, operator, value in conjunction:
[  260s]             if operator == "in" and not isinstance(value, (list, set, tuple)):
[  260s]                 raise TypeError("Value of 'in' filter must be a list, set, or tuple.")
[  260s]             out_parts = []
[  260s]             out_statistics = []
[  260s]             for part, stats in zip(parts, statistics):
[  260s]                 if "filter" in stats and stats["filter"]:
[  260s]                     continue  # Filtered by engine
[  260s]                 try:
[  260s]                     c = toolz.groupby("name", stats["columns"])[column][0]
[  260s]                     min = c["min"]
[  260s]                     max = c["max"]
[  260s]                 except KeyError:
[  260s]                     out_parts.append(part)
[  260s]                     out_statistics.append(stats)
[  260s]                 else:
[  260s]                     if (
[  260s]                         operator in ("==", "=")
[  260s] >                       and min <= value <= max
[  260s]                         or operator == "!="
[  260s]                         and (min != value or max != value)
[  260s]                         or operator == "<"
[  260s]                         and min < value
[  260s]                         or operator == "<="
[  260s]                         and min <= value
[  260s]                         or operator == ">"
[  260s]                         and max > value
[  260s]                         or operator == ">="
[  260s]                         and max >= value
[  260s]                         or operator == "in"
[  260s]                         and any(min <= item <= max for item in value)
[  260s]                     ):
[  260s] E                   TypeError: '<=' not supported between instances of 'NoneType' and 'str'
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:1353: TypeError
[  260s] 
[  260s] The above exception was the direct cause of the following exception:
[  260s] 
[  260s] tmp_path = PosixPath('/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3')
[  260s] engine = 'fastparquet'
[  260s] 
[  260s]     def test_select_filtered_column(tmp_path, engine):
[  260s]     
[  260s]         df = pd.DataFrame({"a": range(10), "b": ["cat"] * 10})
[  260s]         path = tmp_path / "test_select_filtered_column.parquet"
[  260s]         df.to_parquet(path, index=False)
[  260s]     
[  260s]         with pytest.warns(UserWarning, match="Sorted columns detected"):
[  260s] >           ddf = dd.read_parquet(path, engine=engine, filters=[("b", "==", "cat")])
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/dataframe/io/tests/test_parquet.py:4524: 
[  260s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  260s] 
[  260s] args = (PosixPath('/tmp/pytest-of-abuild/pytest-8/popen-gw5/test_select_filtered_column_fa3/test_select_filtered_column.parquet'),)
[  260s] kwargs = {'engine': 'fastparquet', 'filters': [('b', '==', 'cat')]}
[  260s] func = <function read_parquet at 0x7f266697f9a0>
[  260s] 
[  260s]     @wraps(fn)
[  260s]     def wrapper(*args, **kwargs):
[  260s]         func = getattr(self, dispatch_name)
[  260s]         try:
[  260s]             return func(*args, **kwargs)
[  260s]         except Exception as e:
[  260s] >           raise type(e)(
[  260s]                 f"An error occurred while calling the {funcname(func)} "
[  260s]                 f"method registered to the {self.backend} backend.\n"
[  260s]                 f"Original Message: {e}"
[  260s]             ) from e
[  260s] E           TypeError: An error occurred while calling the read_parquet method registered to the pandas backend.
[  260s] E           Original Message: '<=' not supported between instances of 'NoneType' and 'str'
[  260s] 
[  260s] /usr/lib/python3.10/site-packages/dask/backends.py:135: TypeError
[  260s] =============================== warnings summary ===============================

```

</details>

**Minimal Complete Verifiable Example**:

```shell
docker pull opensuse/tumbleweed
docker run -it --name dasktest opensuse/tumbleweed
# (python310-dask* in the main repository is at 2023.1.1 at the moment, but the failure is the same)
zypper install python310-dask-test python310-pytest python310-fastparquet
pytest --pyargs dask -k "test_parquet and test_select_filtered_column and fastparquet"
```

**Environment**:

- Dask version: 2023.2.0
- Python version: Any (3.10.9)
- Fastparquet version: 2023.2.0
- Pandas version: 1.5.3
- Operating System: openSUSE Tumbleweed
- Install method (conda, pip, source): rpm built from sources

**Comment by jrbourbeau** [comment]
Thanks for the issue @bnavigator. I just ran `pytest dask/dataframe/io/tests/test_parquet.py::test_select_filtered_column` locally with `dask` and `fastparquet` 2023.2.0 and things passed. It looks like the error you're seeing was fixed by https://github.com/dask/dask/pull/9772, which was included in the `dask=2023.1.1` release. Could you double check that the expected versions of `dask` and `fastparquet` are being used?

**Comment by bnavigator** [comment]
Hi, yes I am absolutely sure that dask 2023.2.0 and fastparquet 2023.2.0 are used:

```
=================================================== short test summary info ===================================================
FAILED dataframe/io/tests/test_parquet.py::test_select_filtered_column[fastparquet] - TypeError: An error occurred while calling the read_parquet method registered to the pandas backend.
================================ 1 failed, 18 skipped, 10494 deselected, 51 warnings in 7.49s =================================
abuild@skylab:~> pip list 
Package              Version
-------------------- ----------
apipkg               3.0.1
appdirs              1.4.4
asciitree            0.3.3
asttokens            2.2.1
attrs                22.2.0
backcall             0.2.0
bokeh                2.4.3
cachey               0.2.1
certifi              2022.9.24
cffi                 1.15.1
charset-normalizer   3.0.1
click                8.1.3
cloudpickle          2.2.0
contourpy            1.0.6
cramjam              2.6.2
cryptography         39.0.1
cycler               0.11.0
dask                 2023.2.0
decorator            5.1.1
distributed          2023.2.0
entrypoints          0.4
exceptiongroup       1.1.0
execnet              1.9.0
executing            1.2.0
fasteners            0.17.3
fastparquet          2023.2.0
fonttools            4.38.0
fs                   2.4.16
fsspec               2022.11.0
graphviz             0.20.1
greenlet             1.1.3
h5py                 3.8.0
HeapDict             1.0.1
idna                 3.4
imageio              2.21.2
importlib-metadata   6.0.0
iniconfig            0.0.0
ipython              8.9.0
jedi                 0.18.2
Jinja2               3.1.2
jsonschema           4.17.3
kiwisolver           1.4.4
llvmlite             0.39.1
locket               1.0.0
MarkupSafe           2.1.2
matplotlib           3.6.3
matplotlib-inline    0.1.6
mimesis              4.0.0
more-itertools       9.0.0
msgpack              1.0.4
multipledispatch     0.6.0
networkx             2.8.8
numba                0.56.4
numcodecs            0.11.0
numexpr              2.8.4
numpy                1.24.1
olefile              0.46
packaging            23.0
pandas               1.5.3
parso                0.8.3
partd                1.3.0
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.4.0
pip                  22.3.1
pluggy               1.0.0
prompt-toolkit       3.0.36
psutil               5.9.4
ptyprocess           0.7.0
pure-eval            0.2.2
py                   1.11.0
pybind11             2.10.3
pycparser            2.21
Pygments             2.14.0
pyOpenSSL            23.0.0
pyparsing            3.0.9
pyrsistent           0.19.3
pytest               7.2.0
pytest-rerunfailures 10.2
pytest-xdist         3.0.2
python-dateutil      2.8.2
python-snappy        0.6.0
pytz                 2022.7
PyWavelets           1.4.1
PyYAML               6.0
requests             2.28.2
scikit-image         0.19.3
scipy                1.10.0
setuptools           65.6.3
six                  1.16.0
sortedcontainers     2.4.0
sparse               0.13.0
SQLAlchemy           1.4.46
stack-data           0.2.0
tables               3.7.0
tblib                1.7.0
tifffile             2022.10.10
tomli                2.0.1
toolz                0.12.0
tornado              6.2
traitlets            5.9.0
typing_extensions    4.4.0
urllib3              1.26.14
wcwidth              0.2.6
wheel                0.38.4
xarray               2022.12.0
zarr                 2.13.3
zict                 2.2.0
zipp                 3.8.1
```

**Comment by bnavigator** [comment]
Now that you mention #9772: optional pyarrow is not installed.

**Comment by jrbourbeau** [comment]
Just checking in, @bnavigator is this failure still happening. Not sure how much I can help at the moment since I'm not able to reproduce

**Comment by bnavigator** [comment]
@jrbourbeau this is still happening with 2023.3.0 at the openSUSE test build. I believe it is because we have not packaged pyarrow yet, thus it is not available for the test. At least the error message should point to the missing pyarrow, or the function should succeed with a fallback when pyarrow is not available.

**Comment by rjzamora** [comment]
Thanks for raising this @bnavigator - Looks like the write phase of `select_filtered_column` is not setting the `engine` argument, and so CI is not capturing the case where fastparquet is used to write the file.

My guess is that fastparquet is no longer writing out string-column statistics by default, because those statistics are rarely used. I suppose an exception is the case that all values in the row-group are the same string (the focus of that test).

To get that test passing, we can add `stats=True` to the `to_parquet` arguments. However, we should definitely be handling the case that the statistics are missing a bit more gracefully. I'll see what needs to change.
